from state import SupportState
from llm import llm

# Review and refine the agent's response before sending it to the customer
def supervisor_node(state: SupportState):

    # return rejection response without further modification
    if state.get("approval_required") and not state.get("approved"):
        return {
            "response": state["response"]
        }

    prompt = f"""
You are a Senior Customer Support Supervisor.

Your responsibility is to review the response generated by the support agent before it is sent to the customer.

Customer Query:
{state["query"]}

Department:
{state["department"]}

Agent Response:
{state["response"]}

Instructions:
- If the previous conversation contains the answer, state exactly what the user's previous issue was.
- Do not say "I don't know" unless the history is empty.
- Correct any grammatical mistakes.
- Ensure the tone is professional and polite.
- Verify that the response completely addresses the customer's query.
- Do NOT invent new information.
- Do NOT change company policies.
- Return ONLY the final improved response.
"""

    response = llm.invoke(prompt)

    return {
        "response": response.content
    }